package com.apex.dms.ui.navigation

object Routes {
    const val Access = "access"
    const val DealerHome = "dealer/home"
    const val DealerShop = "dealer/shop"
    const val DealerRequests = "dealer/requests"
    const val DealerOrders = "dealer/orders"
    const val DealerProfile = "dealer/profile"
    const val DealerCart = "dealer/cart"
    const val DealerProduct = "dealer/product/{id}"
    const val DealerRequestDetail = "dealer/request/{id}"
    const val DealerQuoteDetail = "dealer/quote/{id}"
    const val DealerOrderDetail = "dealer/order/{id}"

    const val StaffHome = "staff/home"
    const val StaffRequests = "staff/requests"
    const val StaffOrders = "staff/orders"
    const val StaffData = "staff/data"
    const val StaffMore = "staff/more"
    const val StaffRequestDetail = "staff/request/{id}"
    const val StaffQuote = "staff/quote/{id}"
    const val StaffOrderDetail = "staff/order/{id}"
    const val StaffDealerDetail = "staff/dealer/{id}"
    const val StaffProductDetail = "staff/product/{id}"
    const val StaffReports = "staff/reports"
    const val StaffSales = "staff/sales"
    const val StaffActivity = "staff/activity"
    const val StaffIntegrations = "staff/integrations"
    const val StaffSettings = "staff/settings"

    fun dealerProduct(id: String) = "dealer/product/$id"
    fun dealerRequest(id: String) = "dealer/request/$id"
    fun dealerQuote(id: String) = "dealer/quote/$id"
    fun dealerOrder(id: String) = "dealer/order/$id"
    fun staffRequest(id: String) = "staff/request/$id"
    fun staffQuote(id: String) = "staff/quote/$id"
    fun staffOrder(id: String) = "staff/order/$id"
    fun staffDealer(id: String) = "staff/dealer/$id"
    fun staffProduct(id: String) = "staff/product/$id"
}
